### ISSUE TITLE
CMIP6 cleanup needed after code refactoring

### ISSUE THREAD

**Issue by naomi-henderson** [NCAR/intake-esm#111]
Hi all, especially @andersy005 .  Sorry this took so long to report, but have been using the old intake-esm until recently and just noticed these small annoyances in `cmip.py`

**ISSUES:**
There are a few issues with the CMIP6Collection after the latest re-factor.
1. regular expression matching not working for `table_id` and `grid_label`
2. the `version` key values are all disappearing for me when saving the collection 
3. `activity_id` and `institution_id` were set before

**VERSION:**
```
# Name                    Version                   Build  Channel
intake-esm                2019.5.11.post112          pypi_0    pypi
```

**DETAILS:**
1. When `table_id` is AERmonZ, it becomes AERmon and ODAY, CFday become day.
    When `grid_label` is gr1, gr1z, grz or gr2, it becomes gr and gnz becomes gn

2. The `version` key is set correctly in cmip.py: `CMIP6Collection/_get_file_attrs`, but when saving to the intake collection csv file, the `version` key values are all removed (blank). The trouble seems to be a conflict with the name `version` in  `intake`, not in the `intake-esm`. Using another name, e.g. `version_id`, fixes the problem.

**PROPOSED FIX:**
The following lines added to `cmip.py/CMIP6Collection/_get_file_attrs`:
```
        f_split = filepath.split('/')
        fileparts['activity_id'] = f_split[-10]
        fileparts['institution_id'] = f_split[-9]
        fileparts['table_id'] = f_split[-5]
        fileparts['grid_label'] = f_split[-3]
        fileparts['version_id'] = f_split[-2]
```
and the following deleted:
```
        table_id = CMIP6Collection._extract_attr_with_regex(filepath, regex=table_id_regex)
        grid_label = CMIP6Collection._extract_attr_with_regex(file_basename, regex=grid_label_regex)
        version = CMIP6Collection._extract_attr_with_regex(filepath, regex=version_regex) or 'v0'

        fileparts['table_id'] = table_id
        fileparts['grid_label'] = grid_label
        fileparts['version'] = version
```

**Comment by andersy005** [comment]
Hi @naomi-henderson,

Thank you for reporting these annoyances/bugs and proposing straightforward fixes! I will work on it sometime today, and will ping you once they are ready.

**Comment by naomi-henderson** [comment]
@andersy005 , looks like the `version` issue was my own problem - so please leave the name `version`, not `version_id`
thanks!

**Comment by andersy005** [comment]
@naomi-henderson,

> activity_id and institution_id were set before

With #65, it became clear that the assumption we made about the directory structure didn't work for everybody. So, we made a change in how to get some of the attributes including `activity_id`, `institution_id`, etc.. This change consists of specifying these attributes in the YAML file used to build the catalog:

```yaml
name: GLADE-CMIP6
collection_type: cmip6
data_sources:
  CESM2-WACCM-AerChemMIP:
    locations:
      - name: CESM2-WACCM-AerChemMIP-catalog
        loc_type: posix
        direct_access: True 
        urlpath: /glade/collections/cmip/CMIP6/AerChemMIP/NCAR/CESM2-WACCM
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

    extra_attributes:
      mip_era: CMIP6
      activity_id: AerChemMIP
      institution_id: NCAR
```

Here's a full version of YAML file with entries for CMIP6 data @ NCAR: https://github.com/NCAR/intake-esm-datastore/blob/master/collection-input/glade-cmip6-collection.yml

When you get time, can you post the  YAMLl file you are using to build the catalogue?

**Comment by andersy005** [comment]
> When table_id is AERmonZ, it becomes AERmon and ODAY, CFday become day.
When grid_label is gr1, gr1z, grz or gr2, it becomes gr and gnz becomes gn

I can confirm that this is happening on my end too:

```python
In [1]: import intake
In [2]: col = intake.open_esm_metadatastore(collection_name="GLADE-CMIP6")

In [3]: col.df.head()
Out[3]:
                                                 resource resource_type  direct_access activity_id    experiment_id  ... source_id table_id                 time_range variable_id    version
355093  CESM2-PAMIP:CESM2-PAMIP-catalog:posix:/glade/c...         posix           True       PAMIP  pdSST-futAntSIC  ...     CESM2  6hrPlev  200006010000-200106010000          pr  v20190614
355092  CESM2-PAMIP:CESM2-PAMIP-catalog:posix:/glade/c...         posix           True       PAMIP  pdSST-futAntSIC  ...     CESM2  6hrPlev  200006010000-200106010000         psl  v20190614
355089  CESM2-PAMIP:CESM2-PAMIP-catalog:posix:/glade/c...         posix           True       PAMIP  pdSST-futAntSIC  ...     CESM2  6hrPlev  200006010000-200106010000     sfcWind  v20190614
355090  CESM2-PAMIP:CESM2-PAMIP-catalog:posix:/glade/c...         posix           True       PAMIP  pdSST-futAntSIC  ...     CESM2  6hrPlev  200006010000-200106010000         tas  v20190614
355091  CESM2-PAMIP:CESM2-PAMIP-catalog:posix:/glade/c...         posix           True       PAMIP  pdSST-futAntSIC  ...     CESM2  6hrPlev  200006010000-200106010000      zg1000  v20190614

[5 rows x 17 columns]

In [4]: col.df.table_id.unique()
Out[4]:
array(['6hrPlev', 'AERday', 'AERmon', 'Amon', 'CFday', 'Eday', 'Emon',
       'LImon', 'Lmon', 'SIday', 'day', 'fx', 'Omon', 'SImon', 'CFmon',
       'ImonAnt', 'ImonGre', '3hr', '6hrLev', 'Efx', 'Eyr', 'IfxGre',
       'Oday', 'Ofx', 'Oyr', 'E1hr', 'E3hr', 'CFsubhr'], dtype=object)

In [5]: col.df.source_id.unique()
Out[5]:
array(['CESM2', 'CanESM5', 'IPSL-CM6A-LR', 'MIROC6', 'MRI-ESM2-0',
       'GISS-E2-1-G', 'historical', 'GISS-E2-1-H', 'CNRM-CM6-1',
       'CESM2-WACCM', 'AWI-CM-1-1-MR', 'BCC-CSM2-MR', 'BCC-ESM1',
       'FGOALS-f3-L', 'E3SM-1-0', 'EC-Earth3-LR', '1pctCO2',
       'abrupt-4xCO2', 'amip', 'piControl', 'GFDL-AM4', 'GFDL-CM4',
       'SAM0-UNICON', 'CNRM-ESM2-1', 'UKESM1-0-LL', 'EC-Earth3'],
      dtype=object)

In [6]: col.df.grid_label.unique()
Out[6]: array(['gn', 'gr', 'gm'], dtype=object)

In [7]: col.df.activity_id.unique()
Out[7]:
array(['PAMIP', 'CMIP', 'ScenarioMIP', 'AerChemMIP', 'CFMIP', 'LS3MIP',
       'LUMIP'], dtype=object)

In [8]: col.df.institution_id.unique()
Out[8]:
array(['NCAR', 'CCCma', 'IPSL', 'MIROC', 'MRI', 'NASA-GISS',
       'CNRM-CERFACS', 'AWI', 'BCC', 'CAS', 'E3SM-Project',
       'EC-Earth-Consortium', 'NOAA-GFDL', 'SNU', 'MOHC'], dtype=object)
```

and the issue is stemming from these lines:

https://github.com/NCAR/intake-esm/blob/70d90b724ca51dbb5852a7b570c0aaa4f3684fbd/intake_esm/cmip.py#L101-L103

as you pointed out.


We used to have these lines, 

>    f_split = filepath.split('/')
        fileparts['activity_id'] = f_split[-10]
        fileparts['institution_id'] = f_split[-9]
        fileparts['table_id'] = f_split[-5]
        fileparts['grid_label'] = f_split[-3]
        fileparts['version_id'] = f_split[-2]

but as I pointed out, with #62, it's hard to guarantee that everybody's directory structure is the same. That is why we replaced them with the regular expression allowing us not to depend on the directory structure.

I am now looking into a fix for this issue, but it will likely keep the regular expressions in-place.

**Comment by naomi-henderson** [comment]
@andersy005 , hmmm, too bad - that means I have to regenerate the YAML file each time ESGF adds a new activity_id or institution_id to the database (which is still happening).  I am automatically downloading new data to add to our local collection and then using `intake-esm` to generate a local catalog, so I would need to check the YAML file for a proper section prior to making the local catalog.   I am trying to get an end-to-end solution for downloading new data from ESGF, checking its integrity and then converting to zarr, so trying to keep as 'fool'-proof as possible (me being the 'fool' in question)

For now I think I will just generate the keys I need on the fly based on my directory structure and then re-write the local catalog each time.  When I get a change I will probably write a piece of code  which auto-generates a new YAML prior to using intake-esm.

thanks again for this terrific tool!

**Comment by naomi-henderson** [comment]
@andersy005 , one more thing while you are looking at the use of regular expressions. It turns out that not all versions are `r'v\d{4}\d{2}\d{2}'` .   The  `CMIP6.CMIP.CAMS.CAMS-CSM1-0` folks, for example,  used `v1` .  Maybe they will fix it, but there are a disturbing number of idiosyncrasies in the CMIP6 data ... so it was more reliable to get the version from the path. Just my 2 cents

**Comment by andersy005** [comment]
> that means I have to regenerate the YAML file each time ESGF adds a new activity_id or institution_id to the database (which is still happening).

This applies to CMIP6 data @ NCAR. The data keeps appearing on the filesystem. The [YAML file](https://github.com/NCAR/intake-esm-datastore/blob/master/collection-input/glade-cmip6-collection.yml) I linked to was **semi auto-generated** a few weeks ago, but I am pretty certain we've had new datasets on disk since then. We are also interested in ways to automate this process of generating the YAML file since the datasets on disk are not static. 


> When I get a change I will probably write a piece of code which auto-generates a new YAML prior to using intake-esm.

If you are interested in how I automated the YAML file generation, I just uploaded the notebook with details: https://gist.github.com/andersy005/5cc53f9285ae6c0abb2ee573250b4ba9
Let me know if you find it useful, and we can work together on standardizing this functionality.

**Comment by andersy005** [comment]
>  Maybe they will fix it, but there are a disturbing number of idiosyncrasies in the CMIP6 data 

I concur. it's not always guaranteed that everyone is following the official data reference syntax (DRS). 

> so it was more reliable to get the version from the path. Just my 2 cents

I personally am not a big fan of regular expressions. I like their flexibility, but regular expression use comes at a cost too. I will revisit previous implementations and see if regular expressions are really worthwhile. If not, I will see if we can get everything to work without them.

**Comment by naomi-henderson** [comment]
@andersy005 , thanks for your very useful suggestions and your notebook for generating the YAML. 
Could you also post your Jinja2 template file?

**Comment by naomi-henderson** [comment]
nevermind, I found it, thanks!

**Comment by andersy005** [comment]
@naomi-henderson, 

I removed all regular expression matching in #113 except the `version` one. So far, it seems to be working:

```python
In [10]: col.df.grid_label.unique()                                                                                           
Out[10]: 
array(['gn', 'gr', 'grz', 'gnz', 'gra', 'grg', 'gr1', 'gr2', 'gr1z',
       'gr2z', 'gnMVSyfC84507-000912', 'gm'], dtype=object)

In [11]: col.df.version.unique()                                                                                              
Out[11]: 
array(['v20190614', 'v20190528', 'v20190430', 'v20190429', 'v20190306',
       'v20190326', 'v20180914', 'v20181109', 'v20180803', 'v20190311',
       'v20181214', 'v20181212', 'v20190308', 'v20190603', 'v20180830',
       'v20181015', 'v20190403', 'v20190313', 'v20190522', 'v20190415',
       'v20190119', 'v20190125', 'v20190514', 'v20190606', 'v20190531',
       'v20190408', 'v20190419', 'v20190302', 'v20190304', 'v20190507',
       'v20181218', 'v20181122', 'v20190226', 'v20181012', 'v20181016',
       'v20190121', 'v20190315', 'v20190116', 'v20181126', 'v20181213',
       'v20181114', 'v20181127', 'v20181009', 'v20190221', 'v20190613',
       'v20190611', 'v20190530', 'v20190202', 'v20181217', 'v20181227',
       'v20181129', 'v20181202', 'v20181211', 'v1', 'v20190422',
       'v20190508', 'v20181108', 'v20190206', 'v20180608', 'v20190103',
       'v20190605', 'v20180727', 'v20190305', 'v20190118', 'v20181005',
       'v20180802', 'v20181123', 'v20181022', 'v20180808', 'v2',
       'v20190222', 'v20180905', 'v20181017', 'v20180920', 'v20181002',
       'v20180827', 'v20180824', 'v20190410', 'v20190425', 'v20190220',
       'v20190401', 'v20190227', 'v20190320', 'v20190218', 'v20190319',
       'v20190723', 'v20180807', 'v20180301', 'v20180701', 'v20180319',
       'v20190201', 'v20190323', 'v20190314', 'v20180626', 'v20180705',
       'v20181203', 'v20180917', 'v20180814', 'v20181018', 'v20181116',
       'v20181026', 'v20181205', 'v20181206', 'v20181115', 'v20190406',
       'v20190404', 'v20190623', 'v20190219', 'v20190328', 'v20190307',
       'v20190503', 'v20190510', 'v20190620', 'v20190617', 'v20190411',
       'v20181031', 'v20190405', 'v20181106', 'v20190502', 'v20181119',
       'v20181102', 'v20180828', 'v20181107', 'v20190208', 'v20190604',
       'v20190624', 'v20180829'], dtype=object)

In [12]: col.df.table_id.unique()                                                                                             
Out[12]: 
array(['6hrPlev', 'AERday', 'AERmonZ', 'Amon', 'CFday', 'Eday', 'Emon',
       'EmonZ', 'LImon', 'Lmon', 'SIday', 'day', 'fx', 'AERmon', 'Omon',
       'SImon', 'CFmon', 'ImonAnt', 'ImonGre', '3hr', '6hrLev',
       '6hrPlevPt', 'EdayZ', 'Efx', 'Eyr', 'IfxGre', 'Oday', 'Ofx', 'Oyr',
       'E1hr', 'E3hr', 'CFsubhr'], dtype=object)

In [13]: col.df.institution_id.unique()                                                                                       
Out[13]: 
array(['NCAR', 'CCCma', 'IPSL', 'MIROC', 'MRI', 'NASA-GISS',
       'CNRM-CERFACS', 'AWI', 'BCC', 'CAMS', 'CAS', 'E3SM-Project',
       'EC-Earth-Consortium', 'NOAA-GFDL', 'SNU', 'MOHC'], dtype=object)
```

>  It turns out that not all versions are r'v\d{4}\d{2}\d{2}' . The CMIP6.CMIP.CAMS.CAMS-CSM1-0 folks, for example, used v1

```python
In [17]: col.search(institution_id='CAMS').query_results[['time_range', 'variable_id', 'grid_label', 'version']]              
Out[17]: 
          time_range variable_id grid_label version
29182  185001-201412          ps         gn      v1
29183  185001-201412          ts         gn      v1
```

**Comment by andersy005** [comment]
@naomi-henderson,  

Hopefully, #113 fixes all the issues you pointed out. Thank you for the bug report. It's incredibly useful to receive bug reports. Also, it's great to know that intake-esm is useful beyond NCAR!

**Comment by n-henderson** [comment]
Fantastic, @andersy005 !  You even got the 'v?' versions working.  

I tried to include `institution_id` and `activity_id` into my template, but it is complicated by the fact that, on our local machine, we have stored the CMIP6 data with the same directory structure on many drives.  So I was using multiple `location` sections (one for each 8TB drive) in the yaml file.  Each drive has whatever activity_ids and institution_ids that happen to be stored on that drive.  I use the intake-esm collection to then generate a single master directory with links to all of the files for our data server.   

You can see that making a separate entry for each combination of [institution_id, activity_id, location]  creates a large number of entries (and produces that many`tqdm` progress bars!) and generally seems to complicate the very simple task of determining the institution_id and activity_id.  So I am still using the multiple locations, resetting those 2 keys after generating the collection and then overwriting the `~/.intake_esm/collection/cmip6/AR6_PANGEO.cmip6.csv` file.  

Fortunately, when we upload to the cloud I can avoid this issue by storing the zarr files in a common directory (as you do on the glade system at NCAR), will be able to have a single location section and will not have to do the reset/overwrite step.

Any suggestions?  Here is my yaml file:
```
name: AR6_PANGEO
collection_type: cmip6
data_sources:
  fletcher.ldeo.columbia.edu:
    locations:
      - name: dm10_AR6-Omon5
        loc_type: posix
        direct_access: True 
        urlpath: /dm10/naomi/AR6-Omon5
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm11_AR6-Omon6
        loc_type: posix
        direct_access: True 
        urlpath: /dm11/naomi/AR6-Omon6
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm12_AR6-Omon7
        loc_type: posix
        direct_access: True 
        urlpath: /dm12/naomi/AR6-Omon7
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm13_AR6-Amon2
        loc_type: posix
        direct_access: True 
        urlpath: /dm13/naomi/AR6-Amon2
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm13_AR6-Omon7-2
        loc_type: posix
        direct_access: True 
        urlpath: /dm13/naomi/AR6-Omon7-2
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm14_AR6-AERmon2
        loc_type: posix
        direct_access: True 
        urlpath: /dm14/naomi/AR6-AERmon2
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm15_AR6-day2
        loc_type: posix
        direct_access: True 
        urlpath: /dm15/naomi/AR6-day2
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm16_AR6-Omon7-3
        loc_type: posix
        direct_access: True 
        urlpath: /dm16/naomi/AR6-Omon7-3
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm1_AR6-mon-other
        loc_type: posix
        direct_access: True 
        urlpath: /dm1/naomi/AR6-mon-other
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm2_AR6-AERmon
        loc_type: posix
        direct_access: True 
        urlpath: /dm2/naomi/AR6-AERmon
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm3_AR6-Amon
        loc_type: posix
        direct_access: True 
        urlpath: /dm3/naomi/AR6-Amon
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm4_AR6-day
        loc_type: posix
        direct_access: True 
        urlpath: /dm4/naomi/AR6-day
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm5_AR6-other
        loc_type: posix
        direct_access: True 
        urlpath: /dm5/naomi/AR6-other
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm6_AR6-Omon1
        loc_type: posix
        direct_access: True 
        urlpath: /dm6/naomi/AR6-Omon1
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm7_AR6-Omon2
        loc_type: posix
        direct_access: True 
        urlpath: /dm7/naomi/AR6-Omon2
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm8_AR6-Omon3
        loc_type: posix
        direct_access: True 
        urlpath: /dm8/naomi/AR6-Omon3
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

      - name: dm9_AR6-Omon4
        loc_type: posix
        direct_access: True 
        urlpath: /dm9/naomi/AR6-Omon4
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

    extra_attributes:
      mip_era: CMIP6
```

**Comment by andersy005** [comment]
@naomi-henderson, 
> creates a large number of entries (and produces that manytqdm progress bars!

If we make the `tqdm` progress bar optional (basically allow users to opt-in or opt-out in case they have a massive YAML file), would making a separate entry for each combination of [institution_id, activity_id, location] still be a problem?

**Comment by naomi-henderson** [comment]
@andersy005 , but this is 20\*18\*(number of locations) of entries, which in my case is 5,766.  I haven't benchmarked it (perhaps I should) - but do the many separate data searches have so little overhead that this is a feasible option?

Would it be possible instead to set institution_id and activity_id in `cmip.py` as before (assuming the ESGF directory structure), but let these keys be ignored by those who prefer to use a yaml file to reset them?  

Or ... just thinking outload ... dictionaries would allow us to get institution_id from source_id and get activity_id from experiment_id in most cases.  There is one experiment_id contained in two activity_ids ( `piClim-aer`  is in both `AerChemMIP` and `RFMIP`), but this is due to a mistake in the `activity_drs` vs `activity_id` keys and only `RFMIP` is really the correct activity_id for `piClim-aer`.

**Comment by andersy005** [comment]
> Would it be possible instead to set institution_id and activity_id in cmip.py as before (assuming the ESGF directory structure), but let these keys be ignored by those who prefer to use a yaml file to reset them?

After spending time fixing the regular expressions issue, I am in favor of this option. I will merge #113, and will revert back to ESGF directory structure as the default option and let users with a different directory structure override them via YAML.

**Comment by andersy005** [comment]
@naomi-henderson 

> Or ... just thinking outload ... dictionaries would allow us to get institution_id from source_id and get activity_id from experiment_id in most cases.

Since the majority of this information (source_id, institution_id, etc..) if not all of it can be retrieved from https://github.com/WCRP-CMIP/CMIP6_CVs, the dictionary approach is also another doable option..

Now, I am in a dilemma over which approach to choose between the two that you proposed :)

**Comment by andersy005** [comment]
@naomi-henderson, 

When you get time, can you post a snippet of what the new YAML file content would look like for you if we revert back to depending on ESGF directory structure solely? I would like to compare it to see the commonality between your YAML and my version and see what changes would need to be made to the existing codebase to support both use cases.

**Comment by naomi-henderson** [comment]
I would just use the yaml posted in https://github.com/NCAR/intake-esm/issues/111#issuecomment-515724876  - one section for each drive

**Comment by andersy005** [comment]
@naomi-henderson, @aaronspring 

#126  reverts back to depending on ESGF directory structure when parsing CMIP5/CMIP6 attributes. With this change, specifying the root directory should suffice:

```yaml
name: GLADE-CMIP6
collection_type: cmip6
data_sources:
  GLADE-DATA:
    locations:
      - name: CMIP-AP
        loc_type: posix
        direct_access: True 
        urlpath: /glade/collections/cmip/CMIP6
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc
```
I am going to merge it soon. Please give it a try and let me know whether it works for you.
