### ISSUE TITLE
Add support for CMIP6 data in Pangeo's Google Cloud Storage 

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-esm#132]
> How can we make intake-esm work with our cloud datasets?

One way to achieve this is to replicate what I did for the AWS CESM-LENS data. The YAML file used to build the catalog looks like this: https://github.com/NCAR/intake-esm-datastore/blob/master/collection-input/aws-cesm1-le-collection.yml

```
name: AWS-CESM1-LE
collection_type: cesm-aws
data_sources:
  land:
    locations:
      - name: monthly
        loc_type: aws-s3
        direct_access: True
        urlpath: s3://ncar-cesm-lens/lnd/monthly
        file_extension: .zarr
      - name: daily
        loc_type: aws-s3
        direct_access: True 
        urlpath: s3://ncar-cesm-lens/lnd/daily
        file_extension: .zarr 

  ocean:
    locations:
      - name: monthly
        loc_type: aws-s3
        direct_access: True
        urlpath: s3://ncar-cesm-lens/ocn/monthly
        file_extension: .zarr
...
```

For CMIP6 data in the cloud, we could have something like:

```
name: GCS-CMIP6
collection_type: cmip6-gcs
data_sources:
  3hr:
    locations:
      - name: historical 3hourly atmosphere data
        loc_type: gcs
        direct_access: True
        urlpath: gcs://pangeo-data/CMIP6_3hr
        file_extension: .zarr
  monthly:
     locations:
       - name: historical monthly ocean data
         loc_type: gcs
         direct_access: True
         urlpath: gcs://pangeo-data/CMIP6_Omon
         file_extension: .zarr
    
...
```
