### ISSUE TITLE
Support other file formats (.hdf5, no file extension)

### ISSUE THREAD

**Issue by ahuang11** [NCAR/intake-esm#139]
From my understanding, `class NMMESource(BaseSource)` under nmme.py, one can wrangle the data however one intends to.

However, when I try remove all the ".nc" file naming extensions from my files (to mimic the actual dataset I'm trying to implement) and update `filename_template = '{model}.{variable}.{month}.{frequency}.{kind}'`, intake no longer is able to find any files.

```
collection_type:        nmme is an empty dataset. It won't be persisted to disk.
```

A reproducible example:

download.py
```
import os
import pandas as pd

BASE_URL = 'https://ftp.cpc.ncep.noaa.gov/NMME/clim/'

ds = pd.read_html(BASE_URL)[0][0].astype(str)
ds = ds.loc[ds.str.endswith('.nc')]

for fi in ds:
    os.system(f'wget {BASE_URL + fi}')
    os.rename(fi, fi.replace('.nc', ''))
```

nmme.yaml
```
collections:
  nmme:
    collection_columns:
    - resource
    - resource_type
    - direct_access
    - model
    - variable
    - month
    - frequency
    - kind
    - file_fullpath
    - file_basename
    - file_dirname
    order_by_columns:
      - model
      - variable
    required_columns:
      - model
      - variable
```

sources.yaml
```
sources:
  cesm: intake_esm.cesm.CESMSource
  cesm-aws: intake_esm.cesm_aws.CESMAWSSource
  cmip5: intake_esm.cmip.CMIP5Source
  cmip6: intake_esm.cmip.CMIP6Source
  mpige: intake_esm.mpige.MPIGESource
  gmet: intake_esm.gmet.GMETSource
  era5: intake_esm.era5.ERA5Source
  cordex: intake_esm.cordex.CORDEXSource
  nmme: intake_esm.nmme.NMMESource
```

nmme.py
```
""" Implementation for The NMME data holdings """
import os

from tqdm.auto import tqdm

from . import aggregate, config
from .bld_collection_utils import _ensure_file_access, _reverse_filename_format, get_subset
from .collection import Collection, docstrings
from .source import BaseSource


class NMMECollection(Collection):

    __doc__ = docstrings.with_indents(
        """ Builds a NMME collection for data
        stored locally
    %(Collection.parameters)s
    """
    )

    def _get_file_attrs(self, filepath):
        file_basename = os.path.basename(filepath)
        fs = file_basename.split('.')

        keys = list(set(self.columns) - set(['resource', 'resource_type', 'direct_access']))

        fileparts = {key: None for key in keys}
        fileparts['file_basename'] = file_basename
        fileparts['file_dirname'] = os.path.dirname(filepath) + '/'
        fileparts['file_fullpath'] = filepath

        filename_template = '{model}.{variable}.{month}.{frequency}.{kind}'

        f = _reverse_filename_format(file_basename, filename_template)
        fileparts.update(f)

        return fileparts

    
class NMMESource(BaseSource):
    name = 'nmme'
    partition_access = True

    def _open_dataset(self):
        # fields which define a single dataset
        dataset_fields = [
            'model',
            'variable',
            'month',
            'frequency',
            'kind',
        ]

        kwargs = self._validate_kwargs(self.kwargs)

        all_dsets = {}
        ds = get_subset(self.collection_name, self.query)

        file_fullpath_column_name = 'file_fullpath'
        file_basename_column_name = 'file_basename'
        variable_column_name = 'variable'

        df = _ensure_file_access(ds, file_fullpath_column_name, file_basename_column_name)
        grouped = df.groupby(dataset_fields)
        for dset_keys, dset_files in tqdm(
            grouped, desc='dataset', disable=not config.get('progress-bar')
        ):
            dset_id = '.'.join(dset_keys)
            var_dsets = []
            for v_id, v_files in dset_files.groupby(variable_column_name):
                urlpath_ei_vi = v_files[file_fullpath_column_name].tolist()
                dsets = [
                    aggregate.open_dataset_delayed(
                        url,
                        data_vars=[v_id],
                        chunks=kwargs['chunks'],
                        decode_times=kwargs['decode_times'],
                    )
                    for url in urlpath_ei_vi
                ]

                var_dset_i = aggregate.concat_time_levels(
                    dsets,
                    time_coord_name_default=kwargs['time_coord_name'],
                    override_coords=kwargs['override_coords'],
                )
                var_dsets.append(var_dset_i)

            _dset_i = aggregate.merge(dsets=var_dsets)
            all_dsets[dset_id] = _dset_i

        self._ds = all_dsets
```

core.py
```
from .nmme import NMMECollection
...
    collection_types = {
        'cesm': CESMCollection,
        'cesm-aws': CESMAWSCollection,
        'cmip5': CMIP5Collection,
        'cmip6': CMIP6Collection,
        'mpige': MPIGECollection,
        'gmet': GMETCollection,
        'era5': ERA5Collection,
        'cordex': CORDEXCollection,
        'nmme': NMMECollection
    }
```

test.py
```
%matplotlib inline
import intake
import yaml

test = yaml.safe_load('''name: NMME
collection_type: nmme
data_sources:
  NMME-Data:
    locations:
      - name: GLADE
        loc_type: posix
        direct_access: True
        urlpath: /home/nmme/''')

col = intake.open_esm_metadatastore(collection_input_definition=test, overwrite_existing=True)
```
