### ISSUE TITLE
alternative to uuid names

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#26]
It would desirable to generate a unique name reproducibly from a query, such that the same query executed in two different instances returns the same name—rather than all queries yielding unique names.

How?

**Comment by andersy005** [comment]
At first, I thought that one way to do this would be a hash function applied it to a query's values. However, I realized that  a query's values can contain a list of values for instance : 
``` python
query = {'experiment':['20C', 'RCP85'], 'has_ocean_bgc':True}
```
and using a hash function would not work because lists are not immutable.


Ccing @kmpaul. Any thoughts on how to deal with this? For the time being, we are using uuid module to generate a name for a catalog entry. 

For instance, you could get `cesm_dple-cff53aef-6938-4c6e-b6ae-efa5035bed7e` with the following query:

```
query:
        case: null
        component: null
        ctrl_branch_year: null
        date_range: null
        ensemble: null
        experiment: g.e11_LENS.GECOIAF.T62_g16.009
        files: null
        files_basename: null
        files_dirname: null
        grid: null
        has_ocean_bgc: null
        sequence_order: null
        stream: null
        variable: FG_CO2
        year_offset: null
```
