### ISSUE TITLE
adaptation of intake-esm on NCI (Australia)

### ISSUE THREAD

**Issue by fanchic** [NCAR/intake-esm#65]
Hey Guys,
I am trying to use intake-esm on our data center and I am encountering some issues.
The database id organised this way :

/g/data/oi10/replicas/CMIP6/FAMIP/MIROC/MIROC6/faf-heat/r1i1p1f1/Omon/so/gn/v20190311

So  I had to pass the urlpath directory as

/g/data/oi10/replicas/CMIP6/CMIP with a depth of 9 or
/g/data/oi10/replicas/CMIP6 with a depth of 10

I believe depth is hardcoded in the build function in cmip.py

This is my call

collection_definition = {
    'name': 'cmip6_test_collection',
    'collection_type': 'cmip6',
    'data_sources': {
        'root_dir': {
            'name': 'GLADE',
            'loc_type': 'posix',
            'direct_access': True,
            'urlpath': '/g/data/oi10/replicas/CMIP6',
            'exclude_dirs': ['GISS-E2-1-G','day','NASA-GISS'],
        }
    },
}

col=intake.open_esm_metadatastore(collection_input_definition=collection_definition,overwrite_existing=True)

and the error i get

AttributeError: 'str' object has no attribute '_get_entry'

> /g/data/eg3/pfd548/miniconda/envs/py3.6_basic/lib/python3.6/site-packages/intake_esm/cmip.py(173)_parse_directory()
    171         time_range_regex = re.compile(time_range)
    172         df = pd.DataFrame(columns=columns)
--> 173         entry = self._get_entry(directory)
    174         if not entry:
    175             return df

ipdb> self
'/g/data/oi10/replicas/CMIP6/FAFMIP/MIROC/MIROC6/faf-heat/r1i1p1f1/Omon/so/gn/v20190311'

Thanks

**Comment by andersy005** [comment]
@fanchic, 

Yes, you are correct. The depth was hardcoded assuming that the directory structure follows the CMIP6 DRS

```

        Directory structure = <mip_era>/
                                <activity_id>/
                                    <institution_id>/
                                        <source_id>/
                                            <experiment_id>/
                                                <member_id>/
                                                    <table_id>/
                                                        <variable_id>/
                                                            <grid_label>/
                                                                <version>
        With ``depth=9``, we retrieve all directories up to ``grid_label`` level
        Reference: CMIP6 DRS: http://goo.gl/v1drZl
```


Which version of `intake-esm` are you running?

I will look more into this and will get back to you.

**Comment by fanchic** [comment]
@andersy005 

I believe, I am running the latest version
intake-esm                2019.4.26.1                py_0    conda-forge

**Comment by andersy005** [comment]
@fanchic, 

> I had to change that line to entry['mip_era'] = 'CMIP'. 

Now I see what is happening. Your directory structure is a bit different from what intake-esm expects. In light of this, we may need to revisit some of the assumptions made during the implementations, and hard-coded values in some places. As one would have expected, your case shows that there is more than one variant of the directory structure and assuming that everyone has the same directory structure makes intake-esm less flexible for other use cases other than our own at NCAR. 

I will keep look for a fix for this issue and will let you know when I find one.. And sorry for any inconvenience. Your feedback is appreciated!

**Comment by andersy005** [comment]
@fanchic, 
when you get time, can you post the output of:
- `ls /g/data/oi10/replicas/CMIP6`?
- `ls /g/data/oi10/replicas/CMIP6/FAMIP`

? I would like to compare your directory structure to our directory structure:

```bash

/glade/collections/cmip/CMIP6 $ ls
CMIP  ScenarioMIP

glade/collections/cmip/CMIP6/CMIP $ ls
BCC  CAS  CCCma  CNRM-CERFACS  E3SM-Project  EC-Earth-Consortium  IPSL  MIROC  MOHC  MRI  NASA-GISS  NCAR  NOAA-GFDL
```

The more I think about it, I don't think this line ```entry['mip_era'] = 'CMIP'``` is the one causing the culprit.

**Comment by fanchic** [comment]
@andersy005 

Here is the directory structure on NCI:
ls /g/data/oi10/replicas/CMIP6 -->
CMIP  FAFMIP  ScenarioMIP
ls /g/data/oi10/replicas/CMIP6/FAFMIP -->
MIROC
ls /g/data/oi10/replicas/CMIP6/CMIP  -->
AWI  BCC  CAS  CCCma  CNRM-CERFACS  E3SM-Project  EC-Earth-Consortium  IPSL  MIROC  MOHC  MRI  NASA-GISS  NCAR  NOAA-GFDL

I might have a bit of time to see what could be the issue next week. By the way I was at C3DIS last week and I met Julia Kent  ;-)
It was nice to see what you guys are doing at NCAR.

**Comment by fanchic** [comment]
@andersy005 

Hey, it seems that updating pandas has resolved some issues, I am now able to build the catalog.

![Screen Shot 2019-05-16 at 5 02 09 PM](https://user-images.githubusercontent.com/43514504/57833134-b72aa500-77fc-11e9-9051-bb242279366f.png)

Do I need to change config.yaml to get the right ids ?

**Comment by andersy005** [comment]
@fanchic, I am glad to hear that things are somewhat working now

From the entries in your dataframe, it appears that you may have made changes to 

https://github.com/NCAR/intake-esm/blob/57d99a0184f296acec977ab004471cc4faa7bff7/intake_esm/cmip.py#L149-L162

If so, can you post these changes here? Can you post the content of your `collection_definition` input dictionary or YAML file.

**Comment by fanchic** [comment]
@andersy005 

Ok I made some progress, I had to modify two things.

I had to had the model line in the config.yml
  cmip6:
    collection_columns:
    - experiment_id
    - activity_id
    - file_basename
    - file_dirname
    - file_fullpath
    - grid_label
    - institution_id
    - member_id
    - mip_era
    - model
    - source_id
    - table_id
    - time_range
    - variable_id
    - version
    order_by_columns:
      - member_id
      - file_fullpath
    required_columns:
      - member_id
      - experiment_id

and them change the get_entry function:

    def _get_entry(self, directory):
        try:
            entry = {}
            dir_split = directory.split('/')
            #entry['mip_era'] = 'CMIP6'
            #entry['activity_id'] = dir_split[-8]
            #entry['institution_id'] = dir_split[-7]
            #entry['source_id'] = dir_split[-6]
            #entry['experiment_id'] = dir_split[-5]
            #entry['member_id'] = dir_split[-4]
            #entry['table_id'] = dir_split[-3]
            #entry['variable_id'] = dir_split[-2]
            #entry['grid_label'] = dir_split[-1]
            entry['mip_era'] = 'CMIP6'
            entry['activity_id'] = dir_split[-9]
            entry['institution_id'] = dir_split[-8]
            entry['model'] = dir_split[-7]
            entry['source_id'] = dir_split[-7]
            entry['experiment_id'] = dir_slit[-6]
            entry['member_id'] = dir_split[-5]
            entry['table_id'] = dir_split[-4]
            entry['variable_id'] = dir_split[-3]
            entry['grid_label'] = dir_split[-2]
            entry['version'] = dir_split[-1]
            return entry

With those changes, I was able to replicate the different steps described here 👍 
https://intake-esm.readthedocs.io/en/latest/notebooks/cmip5.html#Building-a-CMIP5-Collection-Catalog

**Comment by andersy005** [comment]
@fanchic, 

When you get time, can you give the master branch of `intake-esm` a try and let me know whether it works for you?

**Comment by fanchic** [comment]
@andersy005 

Ok I am testing the master branch.

i created a collection yml file 

```
name: NCI-CMIP6
collection_type: cmip6
data_sources:
  NCI-CMIP:
    locations:
      - name: CMIP-catalog
        loc_type: posix
        direct_access: True 
        urlpath: /g/data/oi10/replicas/CMIP6/CMIP
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc
    extra_attributes:
        mip_era: CMIP6
        activity_id: CMIP
  NCI-ScenarioMIP:
    locations:
      - name: ScenarioMIP-catalog
        loc_type: posix
        direct_access: True 
        urlpath:  /g/data/oi10/replicas/CMIP6/ScenarioMIP
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc
    extra_attributes:
      mip_era: CMIP6
      activity_id: ScenarioMIP
```

then ran

`intake-esm-builder -cdef nci-cmip6-collection.yml --overwrite-existing
`

then I call 

`col = intake.open_esm_metadatastore(collection_name="NCI-CMIP6",overwrite_existing=False)
`
It seems to be working fine but institution_id does not seem to be captured and return NaN in my case.

**Comment by andersy005** [comment]
@fanchic,

Thank you for the feedback! If you are on master branch of `intake-esm`, you no longer have to specify the extra attributes section. Either of the following YAML file would work:

Option 1:

```yaml
name: NCI-CMIP6
collection_type: cmip6
data_sources:
  NCI-CMIP:
    locations:
      - name: CMIP-catalog
        loc_type: posix
        direct_access: True 
        urlpath: /g/data/oi10/replicas/CMIP6/CMIP
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc
  NCI-ScenarioMIP:
    locations:
      - name: ScenarioMIP-catalog
        loc_type: posix
        direct_access: True 
        urlpath:  /g/data/oi10/replicas/CMIP6/ScenarioMIP
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc 
```

Option 2:

```yaml
name: NCI-CMIP6
collection_type: cmip6
data_sources:
  NCI-CMIP6-DATA:
    locations:
      - name: CMIP-catalog
        loc_type: posix
        direct_access: True 
        urlpath: /g/data/oi10/replicas/CMIP6
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

```

> It seems to be working fine but institution_id does not seem to be captured and return NaN in my case.


After building the catalog, can you try the following 

```python
col = intake.open_esm_metadatastore(collection_name="NCI-CMIP6")
print(col.nunique())
print(col.unique(columns='institution_id')
```

Also can you post a full file path for one of the files in your CMIP6 data here? I would like to use it to figure out what might be the root cause for not parsing the institution_id properly.
